# Generated by Django 6.1.1 on 2026-09-25 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Message de Contact',
                'verbose_name_plural': 'Messages de Contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=250)),
                ('institution', models.CharField(max_length=250)),
                ('location', models.CharField(default='Parakou, Bénin', max_length=100)),
                ('start_year', models.CharField(max_length=50)),
                ('end_year', models.CharField(default='En cours', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Parcours Académique',
                'verbose_name_plural': 'Parcours Académiques',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(default='Parakou, Bénin', max_length=100)),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(default='Présent', max_length=50)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Expérience Professionnelle',
                'verbose_name_plural': 'Expériences Professionnelles',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', models.TextField()),
                ('full_description', models.TextField(blank=True)),
                ('technologies', models.CharField(help_text='Séparées par des virgules (ex: Django, Tailwind, PostgreSQL)', max_length=300)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('demo_url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('status', models.CharField(choices=[('completed', 'Terminé'), ('in_progress', 'En cours'), ('archived', 'Archivé')], default='completed', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='GOUNOU Mora Nabil | Portfolio Futursitic', max_length=200)),
                ('primary_color', models.CharField(default='#00f0ff', max_length=50)),
                ('secondary_color', models.CharField(default='#8a2be2', max_length=50)),
                ('bg_color', models.CharField(default='#06070d', max_length=50)),
                ('font_family', models.CharField(default='Space Grotesk', max_length=100)),
                ('enable_3d', models.BooleanField(default=True)),
                ('hero_greeting', models.CharField(default='Bonjour, je suis', max_length=100)),
                ('hero_title', models.CharField(default='GOUNOU Mora Nabil', max_length=150)),
                ('hero_subtitle', models.CharField(default='Développeur Fullstack — Vibe Codeur', max_length=200)),
                ('hero_description', models.TextField(default='Développeur fullstack passionné, je transforme des idées en applications robustes, élégantes et intuitives — avec Django et une bonne dose de créativité.')),
                ('about_text', models.TextField(default="Étudiant en 1ère année de Licence en Systèmes d'Information et Logiciels à l'Institut Universitaire Les Cours Sonou de Parakou (Bénin). Passionné par le code, l'architecture logicielle et les interfaces immersives. Je conçois des solutions web performantes et évolutives.")),
                ('location', models.CharField(default='Parakou, Bénin', max_length=100)),
                ('email', models.EmailField(default='contact@gounounabil.tech', max_length=254)),
                ('phone', models.CharField(default='+229 01 00 00 00 00', max_length=50)),
                ('availability', models.CharField(default='Disponible pour stage, freelance & projets innovants', max_length=150)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resume/')),
            ],
            options={
                'verbose_name': 'Paramètre du Site',
                'verbose_name_plural': 'Paramètres du Site',
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Catégorie de Compétence',
                'verbose_name_plural': 'Catégories de Compétences',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(default='fab fa-github', max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Réseau Social',
                'verbose_name_plural': 'Réseaux Sociaux',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('proficiency', models.IntegerField(default=80)),
                ('icon', models.CharField(default='fas fa-code', help_text='FontAwesome class (e.g. fab fa-python, fas fa-database)', max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.skillcategory')),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
                'ordering': ['category__order', 'order'],
            },
        ),
    ]
