# Generated by Django 6.1.1 on 2026-09-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='fas fa-code', help_text='FontAwesome class (e.g. fas fa-laptop-code, fas fa-server, fab fa-python)', max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
