# Generated by Django 6.1.1 on 2026-09-25 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_service_alter_sociallink_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.CreateModel(
            name='ServiceExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/examples/')),
                ('project_link', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='core.service')),
            ],
            options={
                'verbose_name': 'Exemple de réalisation',
                'verbose_name_plural': 'Exemples de réalisations',
                'ordering': ['order'],
            },
        ),
    ]
