backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "accueil"
    label: "Accueil"
    files:
      - file: "content/accueil.json"
        label: "Contenu Accueil"
        name: "accueil"
        fields:
          - {label: "Titre", name: "title", widget: "string"}
          - {label: "Sous-titre", name: "subtitle", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
